### PR TITLE
Build and portability fixes for 4.7 release

### PR DESCRIPTION
**Pull request by zorun**
This is a set of fixes to the build system that improve portability, especially when packaging `restbed` in Linux distributions.

This is basically a rebased version of #294 + other related fixes (including one from @aberaud ).

### CODE REVIEW

**Comment by zorun** [comment]
Sorry, this PR was intended against the `4.7` branch, not `master`. I have changed the base.

**Comment by zorun** [comment]
Thanks for the merge, but it looks like 2d2ac94ccf8e2c084c3a396b4724b7843fe6d67e (fix for #337) partially reverted these changes...

**Comment by ben-crowhurst** [comment]
The only alteration was the need to specify `-DBUILD_TESTS=YES`, allowing for the reduction in build if-statement logic.

Are you specifically looking for it to enable testing only if the catch dependency is present?

**Comment by zorun** [comment]
The way I implemented it, passing no CMake option means "auto-detect Catch2 and enable tests if it is found". But it is still possible to force (enable or disable) tests by passing the option.

This was explained in the README...

**Comment by ben-crowhurst** [comment]
I personally prefer a caller to be more explicit in her/his intentions.  This remove ambiguity and halts a certain kind of issue being raised.

**Pull request merged**
