### PR TITLE
Fix request->get_path_parameter() 

### PR DESCRIPTION
**Pull request by juliusza**
returning values from previous requests in "keep-alive" connections

### CODE REVIEW

**Comment by juliusza** [comment]
http://www.cplusplus.com/reference/map/map/insert/
> Because element keys in a map are unique, the insertion operation checks whether each inserted element has a key equivalent to the one of an element already in the container, and if so, **the element is not inserted**, returning an iterator to this existing element (if the function returns a value).

**Comment by ben-crowhurst** [comment]
Looks good.  I'll create a regression test and apply.

**Comment by ignitenet-martynas** [comment]
Can I offer help? I.e. try and create a regression test or whatever's missing?

**Comment by ben-crowhurst** [comment]
@ignitenet-martynas if you have free time please do proceed.  Sorry to the delay just looking for some slack to wrap things up.

**Comment by ignitenet-martynas** [comment]
@ben-crowhurst done. I've passed the regression test over to @juliusza and he's added it to his commit.

**Comment by juliusza** [comment]
@ben-crowhurst could you check this PR whenever possible? For us this has caused a security issue, where information was sometimes unintentionally revealed to users. I think this might cause similar problems for other developers.

**Comment by ben-crowhurst** [comment]
Guys I apologise for the delay with regard to this issue.  Things are a bit hectic at the moment.

**Pull request merged**
