### PR TITLE
Add OSX to Continuous Integration

### PR DESCRIPTION
**Pull request by nunojpg**
Note: I don't use OSX, but Travis builds and tests fine.

### CODE REVIEW

**Comment by ben-crowhurst** [comment]
Awesome addition 👍

**Comment by ben-crowhurst** [comment]
Hey the Findopenssl.cmake file is missing

**Comment by ben-crowhurst** [comment]
Reintroducing it causes errors on MacOSX, reverting for now.

**Comment by nunojpg** [comment]
Hi, yes, Findopenssl.cmake was removed according to the commit message at:

https://github.com/Corvusoft/restbed/pull/201/commits/3eb7f2baa2a8d59f3850184ad1e1ffb1302e6d31

Is it failing to work in any situation using the default one provided by cmake?

**Comment by ben-crowhurst** [comment]
Yeah it failed for me locally on a MacOSX installation. At first sight appears to be finding headers from a different location than the binary.

Shall investigate further.

**Comment by nunojpg** [comment]
On travis I need to give a hint for it to find SSL:

OPENSSL_ROOT_DIR=/usr/local/opt/openssl

I didn't know if this was specific to Travis, or if it is just the usual one that is missing on the cmake module.

If you confirm this is the path, we can bake it into CMakeLists, and remove it from the Travis specific config.

**Comment by nunojpg** [comment]
Also, if before this PR it finds OpenSSL on your system, but not on Travis, it means that your system have OpenSSL on a different path... Since I don't use OS X I can't find the reason for that...

**Comment by ben-crowhurst** [comment]
ok i just need to add /usr/local/opt to the Findopenssl.cmake list then. Will give it a shot.

**Comment by ben-crowhurst** [comment]
This seems to have been an error in the original cmake find module.

`find_path( ssl_INCLUDE openssl/ssl.h HINTS "${PROJECT_SOURCE_DIR}/dependency/openssl/inc32" "${PROJECT_SOURCE_DIR}/dependency/openssl/include" "/usr/local/opt/openssl/lib" "/usr/include" "/usr/local/include" "/opt/local/include" )`

Needs to be

`find_path( ssl_INCLUDE openssl/ssl.h HINTS "${PROJECT_SOURCE_DIR}/dependency/openssl/inc32" "${PROJECT_SOURCE_DIR}/dependency/openssl/include" "/usr/local/opt/openssl/include" "/usr/include" "/usr/local/include" "/opt/local/include" )`

**Pull request merged**
