### PR TITLE
Feature/worker thread exception safety

### PR DESCRIPTION
**Pull request by clrusby**
The purpose of this change is so that exceptions when thrown on the worker threads will be caught and propagate back to the master thread.

Otherwise, if the exception is uncaught, the process will (or at least ought to) terminate.  We've seen this happen in some of our apps.

There are many ways to skin this particular cat.  However, we've discussed this fairly thoroughly in-house and feel this is a decent option.

Thanks
Chris

### CODE REVIEW

**Comment by ben-crowhurst** [comment]
Outstanding!

**Comment by arteniioleg** [comment]
Just want to remind that I had similar issue https://github.com/Corvusoft/restbed/pull/270

**Comment by arteniioleg** [comment]
This fixed a problem in my tests. 

I do `service->start()` in a new thread and wait using a promise in `ready_handler`.
Right after that I call `service->stop()`.

Pseudo code:

```
service = make_shared<Service>()

promise;
service->set_ready_handler([&promise](){ promise.set_value() })

thread = [&service]{ service->start() }

promise.get_future().wait_for(seconds{1})

service->stop()
thread->join()
```
This resulted in a crash because `stop()` was doing `join()` in [this loop](https://github.com/Corvusoft/restbed/pull/331/files#diff-15e3f6f629c43b382a5f3b006c8bfef3L109) in main thread but the thread where `start()` was running was still in progress creating new threads, then [this line](https://github.com/Corvusoft/restbed/pull/331/files#diff-15e3f6f629c43b382a5f3b006c8bfef3L114) was crashing because `m_workers` contained new not joined threads.

Now `stop()` waits until all threads have been started.

Thank you!

----

In my tests `ready_handler` is a signal that service is fully started and I do HTTP requests to test my resources. But `ready_handler` is called before the service has started, not after, and in the case of multiple workers it's called [much earlier](https://github.com/Corvusoft/restbed/blob/a1e9c970cf0886ab9e115f776f7d3c5dab52b964/source/corvusoft/restbed/service.cpp#L180-L203).

I was going to create a pull request to move `ready_handler` call after threads have been created, [here](https://github.com/Corvusoft/restbed/blob/a1e9c970cf0886ab9e115f776f7d3c5dab52b964/source/corvusoft/restbed/service.cpp#L204).

Do you think it's a good idea?

**Comment by clrusby** [comment]
@arteniioleg seems like a good idea to me.  Personally, I'm not using the ready handler functionality, but if you've tested it and it works better for you, I'd submit a PR, yes.

**Comment by arteniioleg** [comment]
@clrusby I will try a PR later. Thanks.

----

Right now I found a **bug**: `stop()` is not working in signal handler with multiple workers, it hangs _(and my IDE kills it with exit code 9)_.

```cpp
mService->set_signal_handler(SIGTERM, [this](const int) { mService->stop(); });
mService->set_signal_handler(SIGINT,  [this](const int) { mService->stop(); });
```

With `settings->set_worker_limit(0)` the server stops ok (fast and with log message "Service halted.").

The signal handler is executed but `stop()` hangs.

Can you fix this please?

**Pull request merged**
